/////////////////////////////////////////////////////////////////////////////
// Name:        RegenerationDialog.h
// Author:      Jari Komppa
// Licence:     
//
// Copyright (c) 2005, Jari Komppa
// All rights reserved.
// 
// Redistribution and use in source and binary forms, 
// with or without modification, are permitted provided 
// that the following conditions are met:
//
// - Redistributions of source code must retain the above 
//   copyright notice, this list of conditions and the 
//   following disclaimer.
// - Redistributions in binary form must reproduce the above 
//   copyright notice, this list of conditions and the 
//   following disclaimer in the documentation and/or other 
//   materials provided with the distribution.
// - The authors' names may not be used to endorse or promote 
//   products derived from this software without specific 
//   prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND 
// CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS 
// BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
// TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY 
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
// POSSIBILITY OF SUCH DAMAGE.
//
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 11/06/05 21:14:44

#ifndef _REGENERATIONDIALOG_H_
#define _REGENERATIONDIALOG_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "RegenerationDialog.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10019
#define SYMBOL_REGENERATIONDIALOG_STYLE wxCAPTION
#define SYMBOL_REGENERATIONDIALOG_TITLE _("Regenerating")
#define SYMBOL_REGENERATIONDIALOG_IDNAME ID_DIALOG
#define SYMBOL_REGENERATIONDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_REGENERATIONDIALOG_POSITION wxDefaultPosition
#define ID_GAUGE 10000
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

/*!
 * RegenerationDialog class declaration
 */

class RegenerationDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( RegenerationDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    RegenerationDialog( );
    RegenerationDialog( wxWindow* parent, wxWindowID id = SYMBOL_REGENERATIONDIALOG_IDNAME, const wxString& caption = SYMBOL_REGENERATIONDIALOG_TITLE, const wxPoint& pos = SYMBOL_REGENERATIONDIALOG_POSITION, const wxSize& size = SYMBOL_REGENERATIONDIALOG_SIZE, long style = SYMBOL_REGENERATIONDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_REGENERATIONDIALOG_IDNAME, const wxString& caption = SYMBOL_REGENERATIONDIALOG_TITLE, const wxPoint& pos = SYMBOL_REGENERATIONDIALOG_POSITION, const wxSize& size = SYMBOL_REGENERATIONDIALOG_SIZE, long style = SYMBOL_REGENERATIONDIALOG_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin RegenerationDialog event handler declarations
////@end RegenerationDialog event handler declarations

////@begin RegenerationDialog member function declarations
    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end RegenerationDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

    void UpdateProgress(int newValue);

////@begin RegenerationDialog member variables
    wxGauge* mProgress;
////@end RegenerationDialog member variables
};

#endif
    // _REGENERATIONDIALOG_H_
